name: Docker Build and Publish

on:
  push:
    branches:
      - master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v4
      
    - name: Build react-chat-client:master
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/react-chat-client:master .
      
    - name: Build socketio-server:master
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/socketio-server:master .
      
    - name: Push react-chat-client:master
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-chat-client:master

    - name: Push socketio-server:master
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/socketio-serve:master
