name: Docker Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build-react-chat-client:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build react-chat-client:master
      working-directory: ./react-client
      run: docker build -t leventewolf/react-chat-client:master .

    - name: Push react-chat-client:master
      run: docker push leventewolf/react-chat-client:master
