name: Docker Build and Publish

on:
  push:
    branches:
      - master

jobs:         
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} registry.hub.docker.com

    - name: Build react-chat-client:master
      working-directory: ./react-client
      run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/react-chat-client:master 
      
    - name: Build socketio-server:master
      working-directory: ./socketio-server
      run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/socketio-server:master
      
    - name: Push react-chat-client:master
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-chat-client:master

    - name: Push socketio-server:master
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/socketio-serve:master
